Resources:
    ClubsTable:
        Type: AWS::DynamoDB::Table
        DeletionPolicy: ${self:custom.deletionPolicy.${self:provider.stage}}
        UpdateReplacePolicy: Retain
        Properties:
            TableName: ${self:custom.dynamoDbTablePrefix}-clubs
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
            -   AttributeName: id
                AttributeType: S
            -   AttributeName: visibility
                AttributeType: S
            KeySchema:
            -   AttributeName: id
                KeyType: HASH
            GlobalSecondaryIndexes:
            -   IndexName: ClubsByVisibility
                KeySchema:
                -   AttributeName: visibility
                    KeyType: HASH
                -   AttributeName: id
                    KeyType: RANGE
                Projection:
                    ProjectionType: ALL

    MembersTable:
        Type: AWS::DynamoDB::Table
        DeletionPolicy: ${self:custom.deletionPolicy.${self:provider.stage}}
        UpdateReplacePolicy: Retain
        Properties:
            TableName: ${self:custom.dynamoDbTablePrefix}-members
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
            -   AttributeName: clubId
                AttributeType: S
            -   AttributeName: userId
                AttributeType: S
            KeySchema:
            -   AttributeName: clubId
                KeyType: HASH
            -   AttributeName: userId
                KeyType: RANGE

Outputs:
    DDBTableClubs:
        Value: !Ref ClubsTable
    DDBTableMembers:
        Value: !Ref MembersTable
